### ISSUE TITLE
Custom image size preset not appearing in popover

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-asset-admin#1033]
## Overview
https://github.com/silverstripe/silverstripe-asset-admin/issues/961 implemented a new way to quickly select pre-defined image sizes, with the options to set custom ones.

When following [the instructions](https://docs.silverstripe.org/en/4/developer_guides/forms/field_types/htmleditorfield/#image-size-pre-sets) to create a custom preset size, it appears in the Asset-admin component, but not the pop-over in TinyMCE. Specifically:

See it present in the asset-admin component:
![image](https://user-images.githubusercontent.com/15868440/70295442-e7df3400-184b-11ea-9097-f0a812746be6.png)

But not the popover:
![image](https://user-images.githubusercontent.com/15868440/70295466-01807b80-184c-11ea-98cb-fcfcdf933ee9.png)

## Expected behaviour
If a custom image size preset is created, it should be visible in both the assest admin and the TinyMCE popover

**Comment by brynwhyman** [comment]
Perhaps this is a Framework issue? It seemed to make sense raising here though...

**Comment by brynwhyman** [comment]
Note, the instructions followed was setting the following YML config:
```
SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  image_size_presets:
    - name: widesize
      i18n: SilverStripe\Forms\HTMLEditor\TinyMCEConfig.WIDE_SIZE
      text: Wide size
      width: 900
```
