### ISSUE TITLE
CMS 6 REGRESSION: SVG as images give a error in generateThumbnail

### ISSUE THREAD

**Issue by Oliver996** [silverstripe/silverstripe-asset-admin#1571]
### Module version(s) affected

3.0.0-rc1 and older Version for SilverStripe 6

### Description

We use SVG in SilverStripe for a long time. We added them like that:
```yml
SilverStripe\Assets\File:
  file_types:
    svg: 'SVG Datei'
  allowed_extensions:
      - svg
  app_categories:
    image:
      - webp
    image/supported:
      - svg
  class_for_file_extension:
    svg: 'SilverStripe\Assets\Image'
```
That worked without problems to SilverStripe version 5.4. But since version 6 there comes an error when you open the folder in assets or try to choose existing from upload field and an SVG image is present in the folder. The ThumbnailGenerator returns an error Uncaught Error: Call to a member function getAllowsAnimationInManipulations() on null.

I could simply solve it with adding this to the ThumbnailGenerator in generateThumbnail() after the first if:
```php
if($file->getExtension() == 'svg'){
    $method = $this->config()->get('method');
    return $file->$method($width, $height);
}
```

I don't really know if this is the best solution. But it looks like the new added animation stuff in the generateThumbnail() does trigger this error for SVG. Is there are a way to tell SilverStripe that SVG do not have any animations? Or could you add something like that?

### How to reproduce

Add SVG:
```yml
SilverStripe\Assets\File:
  file_types:
    svg: 'SVG Datei'
  allowed_extensions:
      - svg
  app_categories:
    image:
      - webp
    image/supported:
      - svg
  class_for_file_extension:
    svg: 'SilverStripe\Assets\Image'
```

Upload image in assets-admin in a folder.

### Possible Solution

Ignore SVG in ThumbnailGenerator in generateThumbnail().

Example:
```php
if($file->getExtension() == 'svg'){
    $method = $this->config()->get('method');
    return $file->$method($width, $height);
}
```

### Validations

- [x] Check that there isn't already an issue that reports the same bug
- [x] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-assets/pull/689
