### ISSUE TITLE
Migrate existing translations from `cms` module

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#239]
`cms/lang/*.yml` contains a handful of translations which we should reuse in AssetAdmin, see some potentials below. Note that we can't _remove_ them from `cms` since translations are only additive (not SS release specific). 

We might need to move some of these from YAML/PHP to JS in order to make use of them. Ideally we can have one source format for _all_ translations (YAML?), and then transform the full set into YAML and JS at the same time, so the translations can be used on client and server. The file size overhead would be fairly small.

Not doing this means about 30 individual translators will need to go through around 20 strings again, and international users likely won't have good translations until later in the 4.x release cycle.

```
en:
  AssetAdmin:
    ADDFILES: 'Add Files'
    ActionAdd: 'Add folder'
    AppCategoryArchive: Archive
    AppCategoryAudio: Audio
    AppCategoryDocument: Document
    AppCategoryFlash: Flash
    AppCategoryImage: Image
    AppCategoryVideo: Video
    BackToFolder: 'Back to folder'
    CMSMENU_OLD: 'Files (old)'
    CREATED: Date
    CurrentFolderOnly: 'Limit to current folder?'
    DetailsView: Details
    FILES: Files
    FILESYSTEMSYNC: 'Sync files'
    FILESYSTEMSYNCTITLE: 'Update the CMS database entries of files on the filesystem. Useful when new files have been uploaded outside of the CMS, e.g. through FTP.'
    FROMTHEINTERNET: 'From the internet'
    FROMYOURCOMPUTER: 'From your computer'
    Filetype: 'File type'
    ListView: 'List View'
    MENUTITLE: Files
    NEWFOLDER: NewFolder
    SIZE: Size
    THUMBSDELETED: '{count} unused thumbnails have been deleted'
    TreeView: 'Tree View'
    Upload: Upload
  AssetAdmin_DeleteBatchAction:
    TITLE: 'Delete folders'
  AssetAdmin_Tools:
    FILTER: Filter
  AssetAdmin_left_ss:
    GO: Go
  AssetTableField:
    BACKLINKCOUNT: 'Used on:'
    PAGES: page(s)
  Folder:
    AddFolderButton: 'Add folder'
    DELETEUNUSEDTHUMBNAILS: 'Delete unused thumbnails'
    UNUSEDFILESTITLE: 'Unused files'
    UNUSEDTHUMBNAILSTITLE: 'Unused thumbnails'
    UploadFilesButton: Upload
```
