### ISSUE TITLE
Move i18n translation strings from cms/framework to asset-admin

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-asset-admin#384]
These will mostly be legacy use, but we need to go through them one-by-one and ensure anything used by the asset-admin is also placed in its own `lang/` folder. This also means moving translations, and pushing them back to transifex (to avoid creating extra work for translators on already translated strings)

`framework/lang/en.yml`

```
AssetAdmin:
    ALLOWEDEXTS: 'Allowed file upload extensions'
    HIDEALLOWEDEXTS: 'Hide allowed extensions'
    NEWFOLDER: NewFolder
    SHOWALLOWEDEXTS: 'Show allowed extensions'
```

`cms/lang/en.yml`

```
AssetAdmin:
    ADDFILES: 'Add Files'
    ActionAdd: 'Add folder'
    AppCategoryArchive: Archive
    AppCategoryAudio: Audio
    AppCategoryDocument: Document
    AppCategoryFlash: Flash
    AppCategoryImage: Image
    AppCategoryVideo: Video
    BackToFolder: 'Back to folder'
    CMSMENU_OLD: 'Files (old)'
    CREATED: Date
    CurrentFolderOnly: 'Limit to current folder?'
    DetailsView: Details
    ErrorItemPermissionDenied: 'It seems you don''t have the necessary permissions to add {ObjectTitle} to a campaign'
    ErrorNotFound: 'That {Type} couldn''t be found'
    FILES: Files
    FILESYSTEMSYNC: 'Sync files'
    FILESYSTEMSYNCTITLE: 'Update the CMS database entries of files on the filesystem. Useful when new files have been uploaded outside of the CMS, e.g. through FTP.'
    FROMTHEINTERNET: 'From the internet'
    FROMYOURCOMPUTER: 'From your computer'
    Filetype: 'File type'
    ListView: 'List View'
    MENUTITLE: Files
    NEWFOLDER: NewFolder
    SIZE: Size
    THUMBSDELETED: '{count} unused thumbnails have been deleted'
    TreeView: 'Tree View'
    Upload: Upload
  AssetAdmin_DeleteBatchAction:
    TITLE: 'Delete folders'
  AssetAdmin_Tools:
    FILTER: Filter
  AssetAdmin_left_ss:
    GO: Go
  AssetTableField:
    BACKLINKCOUNT: 'Used on:'
    PAGES: page(s)
```
