### ISSUE TITLE
Permalink for assets

### ISSUE THREAD

**Issue by caffeineinc** [silverstripe/silverstripe-asset-admin#855]
The asset admin area doesn't currently support permalinks - that is a link to download a file that never changes. 

I believe there's a fairly common use case for CMS users to modify versions of files on a common basis, especially if referenced within several pages in the CMS. Those pages in the CMS can find the updated image because they're based of the ORM and have references to the file object, but the system is currently missing linking options for external systems such as confluence linking to an intranet. 

In this case, it would be extremely useful to have a reference for the file, which always returns the most recent version of that file.

**Comment by madmatt** [comment]
+1 Definitely agree, and could hopefully be handled quite easily by replacing the hash with `permalink` or some other word without disabling file versioning entirely (which I suppose would be the other less-desirable answer).

**Comment by maxime-rainville** [comment]
I think we need to think about wider implication regarding this to make sure we develop a flexible solution that will meet multiple needs. e.g.:
* Do we want a "Wikipedia-style" permalink that allows you to recover a file as it existed at any given state.
* Do we want to work off the Filename as shown in the CMS? Do we want to work off the ID?
* When inserting the file in a WYSWIYG, do we want to keep using the current file format? or the permalink? or make it configurable?

# Short term fix

I've got an easy fix that developers can apply to their install if they need a solution right away? Basically, you extend the default asset file store and add a bit of logic to try to see if the URL matches a FileFileName for an existing file.

@tractorcow @unclecheese @robbieaverill I've tested it locally and it doesn't look like this allows access to files that have not been published, but it's probably worth having a second opinion on this.  

```php
<?php

use SilverStripe\Assets\File;
use SilverStripe\Assets\Flysystem\FlysystemAssetStore;

class CustomAssetStore extends FlysystemAssetStore {

    public function getResponseFor($asset)
    {
        /**
         * @var File
         */
        $file = File::get()->filter(['FileFilename' => $asset])->first();
        if ($file) {
            $asset = $file->File->getSourceURL();
            $asset = preg_replace('/^\/?assets\//i', '', $asset);
        }

        return parent::getResponseFor($asset);
    }
}
```

You need this bit in your YML config
```yml
---
Name: customassets
After:
  - '#assetscore'
---
SilverStripe\Core\Injector\Injector:
  # Define our SS asset backend
  SilverStripe\Assets\Storage\AssetStore:
    class: CustomAssetStore
    properties:
      PublicFilesystem: '%$League\Flysystem\Filesystem.public'
      ProtectedFilesystem: '%$League\Flysystem\Filesystem.protected'
```
